# Generated by Django 3.0.7 on 2020-06-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='modified_date',
            field=models.DateTimeField(),
        ),
    ]
