# Generated by Django 3.0.7 on 2020-06-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200611_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='modified_date',
            field=models.DateTimeField(null=True),
        ),
    ]
