# Generated by Django 3.0.7 on 2020-06-11 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200611_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='modified_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
