# Generated by Django 3.0.7 on 2020-06-11 14:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200611_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='related_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Blog'),
            preserve_default=False,
        ),
    ]
